### ISSUE TITLE
Feature Request: http.Handler test runner

### ISSUE THREAD

**Issue by siggimoo** [jefflinse/melatonin#1]
Presently, test runners only work with actual network calls against a TCP-accessible server process. It would be helpful for unit testing purposes to be able to use `itest` with an `http.Handler` as well.

For instance, I would like to be able to do something like the following:

```
func TestGetUserList(t *testing.T) {
    testUser := User{
        Name: "John Doe",
        Email: "jdoe@null.com",
    }
    userRepository := newMockUserRepoWith(testUser)

    router := newMuxRouterWithAPI(userRepository)
    itest.RunTests(router, []*itest.TestCase{
        itest.GET("/users").
            Describe("Fetch user list").
            ExpectStatus(200).
            ExpectBody(`[{"name":"John Doe","email":"jdoe@null.com"}]`),
    })
}
```

**Comment by jefflinse** [comment]
Hmm, I like the idea, but as this framework is intended for blackbox testing (integration and e2e tests), the more pragmatic approach for your scenario would be to use [httptest](https://pkg.go.dev/net/http/httptest) for this, e.g.:

```go
func TestGetUserList(t *testing.T) {
    testUser := User{
        Name: "John Doe",
        Email: "jdoe@null.com",
    }
    userRepository := newMockUserRepoWith(testUser)

    router := newMuxRouterWithAPI(userRepository)
    server := httptest.NewServer(router)
    defer server.Close()

    itest.RunTests(server.URL, []*itest.TestCase{
        itest.GET("/users").
            Describe("Fetch user list").
            ExpectStatus(200).
            ExpectBody(`[{"name":"John Doe","email":"jdoe@null.com"}]`),
    })
}
```

This accomplishes the same thing, but keeps the concerns of handling requests separate from the test framework.

**Comment by siggimoo** [comment]
The problem I have with this suggestion is `httptest.Server` involves the OS network stack, even if it's just localhost. That's superfluous for unit testing and a potential point of failure. What I'm after is a tool for testing the web-layer of an application in isolation. If that's out of scope for your package then please disregard.

**Comment by jefflinse** [comment]
You make a good point about being able to bypass the network stack. Although it wasn't part of my original intent, I decided to support this scenario since it's pretty low effort / high reward. Now you can choose what you want to test: an endpoint or a handler:

```go
runner := itest.NewEndpointTester("https://example.com")
runner.RunTests(...)
```

```go
runner := itest.NewHandlerTester(http.NewServeMux())
runner.RunTests(...)
```

The latter accepts any `http.Handler`, calls `ServeHTTP()` directly on the handler and uses an `httptest.ResponseRecorder` to capture the results.

Convenience functions have been changed to
- `TestEndpoint(baseURL string, tests []*itest.TestCase)`
- `TestEndpointT(t *testing.T, baseURL string, tests []*itest.TestCase))`
- `TestHandler(handler http.Handler, tests []*itest.TestCase))`
- `TestHandlerT(t *testing.T, handler http.Handler, tests []*itest.TestCase))`
